WIP

diff --git a/scripts/netnsinit b/scripts/netnsinit
--- a/scripts/netnsinit
+++ b/scripts/netnsinit
@@ -194,9 +194,52 @@ autoconfigure() {
 	return 0
 }
 
-if [ $# == 0 ]; then
+inside_check() {
+        NSTYPE=$1
+
+        GLOBAL_NETNS_ID="$(readlink /proc/1/ns/net)"
+        if [[ -z "$GLOBAL_NETNS_ID" ]]; then
+          echo "Failure to get global netns ID."
+          exit 1
+        fi
+
+        CURRENT_NETNS_ID="$(readlink /proc/$$/ns/net)"
+        if [[ -z "$CURRENT_NETNS_ID" ]]; then
+          echo "Failure to get current netns ID."
+          exit 1
+        fi
+
+        NEWPID=$(systemctl show --value -p MainPID netns-new@$NSTYPE.service)
+        if [[ -z "$NEWPID" || "$NEWPID" == "0" || ! -h /proc/$NEWPID/ns/net ]]; then
+          echo "Failure to get PID of netns-new@$NSTYPE.service."
+          exit 1
+        fi
+
+        INSIDE_NETNS_ID="$(readlink /proc/$NEWPID/ns/net)"
+        if [[ -z "$INSIDE_NETNS_ID" ]]; then
+          echo "Failure to get netns ID of netns-new@$NSTYPE.service."
+        fi
+
+        if [[ "$CURRENT_NETNS_ID" == "$GLOBAL_NETNS_ID" ]]; then
+          echo "Current netns is the global netns!"
+          exit 1
+        fi
+
+        if [[ "$CURRENT_NETNS_ID" != "$INSIDE_NETNS_ID" ]]; then
+          echo "Current netns is not the same as the netns of netns-new@$NSTYPE.service!"
+          exit 1
+        fi
+
+        echo "Running in the expected netns."
+}
+
+if [[ $# != 3 ]]; then
 	display_usage
 	exit 1
+fi
+
+if [[ "$3" == "inside" ]]; then
+  inside_check "$1"
 fi
 
 case "$1" in
